### ISSUE TITLE
Error rendering solid-js application (laravel 9.x, solid-js 1.7.5)

### ISSUE THREAD

**Issue by lighth7015** [iksaku/inertia-adapter-solid#4]
Good morning!

I'm attempting to SSR render a site I'm writing using laravel and solid-js, but when I access the page and the following response when I attempt to access the SSR server directly,

`implode(): Argument #2 ($array) must be of type ?array, string given`

```
status:    "NOT_FOUND"
timestamp: 1697101285353
```

I've followed the directions for setting the adapter up to a tee, and the result is the error I receive as a result.

Any suggestions what I could be doing wrong? Thank you!

**Comment by iksaku** [comment]
Hello, this seems to be a PHP error, nothing to do with this adapter. 
Which PHP framework are you using?

**Comment by lighth7015** [comment]
laravel 9, and according to some folks on the solidjs discord, the adapter isn't 100% following the SSR protocol.

**Comment by lighth7015** [comment]
I can somewhat confirm this, as I had to patch their HTTP proxy code to make sure that if `$response["header"]` isn't an array, that it's just supposed to return it verbatim, rather than trying to join it.

If you have time, I'm on the solidjs discord (robert_), you can ping me there- or I can go gather debug logs if you'd prefer 😅😅

**Comment by iksaku** [comment]
Kindly point me to the discussion to have better context on this as, to me, it seems that the problem is not related to this adapter but to inertia itself

**Comment by iksaku** [comment]
Found the discussion thread: https://discord.com/channels/592327939920494592/758259460920573992/1161998154481274981

It is indeed as you mention, this adapter does not return an array of headers, but a string as it is rendered directly using [`solid-meta` package](https://github.com/solidjs/solid-meta/blob/c9d21efc62fcb4df1205d849b0a3abfa3623fcf8/src/index.tsx#L220-L244).

If you have any suggestions, please let me know, I'm a little bit busy atm so it may take me a few days

**Comment by iksaku** [comment]
@lighth7015 please let me know if this recent release fixes your issues 🙌
