### ISSUE TITLE
index.jsx:147  Uncaught (in promise) ReferenceError: React is not defined

### ISSUE THREAD

**Issue by SaidiYusof** [iksaku/inertia-adapter-solid#7]
I'm running Laravel 11 with vite, inertia (inertia-adapter-solid), and solid-js, there is an error 'Uncaught (in promise) ReferenceError: React is not defined'. 

When I checked all my files, it was found to have nothing to do with the 'React' component

Why is the error command displayed, it has no relationship with 'React'

**Comment by RomainLanz** [comment]
Hey @SaidiYusof! 👋🏻 

You probably have a react reference inside your `tsconfig.json`.
Can you double-check the `jsxImportSource` property and ensure it is set to `solid-js`?

**Comment by iksaku** [comment]
Closing as @RomainLanz commented the solution 😄
